# Generated by Django 4.1.7 on 2023-03-07 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffeeshops', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coffeeshop',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
