# Generated by Django 4.1.7 on 2023-03-07 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coffeeshops', '0002_alter_coffeeshop_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='user',
        ),
    ]
